import './globals.css';
import { Nunito } from 'next/font/google';
import Navbar from '@/components/navbar';

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '500', '700', '300', '600'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} min-h-screen bg-mauve-2 text-mauve-12`}
      >
        <Navbar />
        <main className="m-auto max-w-4xl p-4">{children}</main>
      </body>
    </html>
  );
}
