import './globals.css';
import { Inter_Tight } from 'next/font/google';
import Navbar from '@/components/navbar';

const inter = Inter_Tight({
  subsets: ['latin'],
  weight: ['400', '500', '700', '300', '600', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen bg-mauve-2 text-mauve-12`}
      >
        <Navbar />
        <main className="m-auto max-w-4xl p-4 pt-8 antialiased">
          {children}
        </main>
      </body>
    </html>
  );
}
